---
weight: 1

title: "Εισαγωγή"
linkTitle: "Εισαγωγή"
author: "Alex"
date: "12/25/2020"
description: >
  Σύντομη περιγραφή της γλώσσας, δυνατότητες και χαρακτηριστικά. Μορφή ενός YAML αρχείου, βασικοί κανόνες σύνταξης.
---


## Περιγραφή

Όπως είπαμε η YAML είναι μία γλώσσα προγραμματισμού σειριοποίησης δεδομένων. Όμως δεν κάνει τίποτε άλλο από αυτά που μπορούν να κάνουν οι συνήθεις γλώσσες προγραμματισμού. Με τη YAML δεν μπορούμε να δομήσουμε έναν ολοκληρωμένο κώδικα που να λαμβάνει εισόδους και να παράγει αποτέλεσμα, όπως οι κοινές γλώσσες προγραμματισμού (Python, C, R κ.λπ.). Αυτό γιατί δε διαθέτει εντολές που να μπορούν να κάνουν κάτι τέτοιο ούτε και κάποιο compiler ή interpreter για να μεταφράζουν τέτοιες εντολές. Με το ίδιο σκεπτικό, δεν μπορεί να χαρακτηριστεί και σαν markup γλώσσα (εξάλλου αυτό σημαίνουν τα αντίστοιχα αρχικά YAML -- YAML Ain't Markup Language) γιατί δεν μπορεί να χρησιμοποιηθεί για τη σήμανση κειμένου (αυτό κάνουν, με απλά λόγια, οι markup γλώσσες όπως οι Latex, Markdown, XML κ.λπ.).

Αν τα παραπάνω είναι αλήθεια, τότε γιατί τη χαρακτηρίζουμε σαν γλώσσα προγραμματισμού; Με τη YAML αυτό που κάνουμε είναι να *περιγράφουμε* δεδομένα. Αυτό και μόνο αυτό κάνει η YAML. Ο χρήστης ή ένα υπολογιστικό σύστημα, μπορεί να περιγράψει τα δεδομένα του σε κάποιο αρχείο, με συγκεκριμένο και συστηματικό τρόπο. Από τη στιγμή που θα το κάνει, ένας κατάλληλος αναλυτής (parser) μπορεί να "μεταφράσει" τα δεδομένα σε ένα αρχείο YAML, σε μορφή που να είναι κατάλληλη και αναγνωρίσιμη από μία γλώσσα προγραμματισμού. Για το σκοπό αυτό υπάρχουν parsers της YAML για σχεδόν όλες τις γνωστές γλώσσες προγραμματισμού.

Θα δούμε περισσότερες λεπτομέρειες για τα αρχεία της YAML στη συνέχεια.

## Χαρακτηριστικά

Τα βασικά χαρακτηριστικά της γλώσσας είναι:

- Χρησιμοποιείται για να περιγράψει δομές δεδομένων με τρόπο που να είναι εύκολα αναγνωρίσιμος και κατανοητός από τον άνθρωπο. Δεν πρέπει να χεχνάτε ότι ο άνθρωπος είναι αυτός που δημιουργεί και διαχειρίζεται αυτά τα δεδομένα!
- Ο τρόπος που ορίζονται τα δεδομένα σε ένα αρχείο YAML καθορίζεται από κενούς χαρακτήρες (space). Θυμίζουμε ότι ο βασικός τρόπος εισαγωγής κενών χαρακτήρων σε ένα αρχείο είναι μέσω των πλήκτρων:
  
  - `space`, εισάγει έναν κενό χαρακτήρα, κάθε φορά που το πατάμε.
  - `tab`, εισάγει πολλαπλούς κενούς χαρακτήρες (συνήθως 2 ή 4 ή 8 ανάλογα με τις ρυθμίσεις του αντίστοιχου επεξεργαστή κειμένου) αλλά *δεν είναι* ισοδύναμος με το `space`.
  - `enter`, εισάγει μία αλλαγή γραμμής κάθε φορά που το πατάμε.
  
{{% alert title="Προσοχή!" color="warning" %}}

Δώστε ιδιαίτερη προσοχή στο πλήκτρο καθώς δεν αντιμετωπίζεται με τον ίδιο τρόπο από τους επεξεργαστές κειμένου και τους αντίστοιχους parsers. **Μην χρησιμοποιείτε** το `tab` όταν γράφετε σε αρχείο YAML.

{{% /alert %}}
  




